# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# set working directory
WORKDIR /app

# copy all files
COPY . .

# install build dependencies and build
RUN apk add --no-cache git python3 make g++ \
    && npm install \
    && npm run build \
    && apk del git python3 make g++

# default command
CMD ["node", "dist/index.js"]
