openapi: 3.1.0
info:
  version: 1.0.0
  title: Swit Open API Documentation
  description: 'The Core API v1 is our initial API, enabling developers to interact with various Swit resources, such as workspaces, channels, projects, tasks, messages, and users. It serves as a practical tool for integrating your own application with Swit to boost team collaborations. Please note, the Core API v1 is slated for deprecation as we transition to Core API v2.'
  termsOfService: 'https://swit.io/privacy?sub=api-term'
  contact:
    name: Swit User & Developer Support
    url: 'https://help.swit.io/?support=true'
    email: help@swit.io
  license:
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
    name: Apache 2.0
servers:
  - url: 'https://openapi.swit.io/v1'
    description: Production
  - url: 'https://openapi.swit.express/v1'
    description: Stage
  - url: 'https://openapi2.swit.dev/v1'
    description: Development
paths:
  /api/user.info:
    get:
      tags:
        - User
      summary: Get user information
      description: Retrieves the authorizing user's basic account information.
      operationId: user.info
      security:
        - OAuth2Application:
            - 'user:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/user.info.update:
    post:
      tags:
        - User
      summary: Update the user's profile
      description: Updates the authorizing user's profile.
      operationId: user.info.update
      security:
        - OAuth2Application:
            - 'user:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
  /api/presence.sync.info:
    get:
      tags:
        - User
      summary: Get the user's presence sync setting
      description: "Whether or not a `/api/presence.status.update` request can update the user's presence sync setting for your app. In UI, users can view or change this setting in User Settings > Connected apps."
      operationId: presence.sync.info
      security:
        - OAuth2Application:
            - 'presence:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
  /api/presence.status.update:
    post:
      tags:
        - User
      summary: Update the user presence
      description: Updates the authorizing user's presence status.
      operationId: presence.status.update
      security:
        - OAuth2Application:
            - 'presence:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
  /api/presence.sync.update:
    post:
      tags:
        - User
      summary: Toggle presence sync
      description: Set whether to allow your app to update the authorizing user's presence status via API.
      operationId: presence.sync.update
      security:
        - OAuth2Application:
            - 'presence:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
  /api/workspace.info:
    get:
      tags:
        - Workspace
      summary: Get workspace info
      description: Retrieves information about a workspace.
      operationId: workspace.info
      security:
        - OAuth2Application:
            - 'workspace:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/workspace.list:
    get:
      tags:
        - Workspace
      summary: List out workspaces
      description: "Lists out a given number of workspaces the user joined. This method uses the Swit API's [pagination scheme](/docs/core1/up49a503iuknu-pagination-scheme)."
      operationId: workspace.list
      security:
        - OAuth2Application:
            - 'workspace:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/workspace.update:
    post:
      tags:
        - Workspace
      summary: Update a workspace
      description: Updates an existing workspace.
      operationId: workspace.update
      security:
        - OAuth2Application:
            - 'workspace:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/workspace.user.info:
    get:
      tags:
        - Workspace
      summary: Get a workspace member's profile
      description: Retrieves a user's profile registered in a given workspace.
      operationId: workspace.user.info
      security:
        - OAuth2Application:
            - 'workspace:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/workspace.user.list:
    get:
      tags:
        - Workspace
      summary: List out workspace members
      description: "Lists out a given number of members from a workspace. This method uses the Swit API's [pagination scheme](/docs/core1/up49a503iuknu-pagination-scheme)."
      operationId: workspace.user.list
      security:
        - OAuth2Application:
            - 'workspace:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/organization.workspace.invite:
    post:
      tags:
        - Workspace
      summary: Invite a member
      description: Invites a member to the workspace.
      operationId: organization.workspace.invite
      security:
        - OAuth2Application:
            - 'workspace:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
  /api/workspace.group.list:
    get:
      tags:
        - Workspace
      summary: Retrieve a workspace's list of groups
      description: Retrieves a list of groups in a workspace
      operationId: workspace.group.list
      security:
        - OAuth2Application:
            - 'workspace:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
  /api/workspace.group.invite:
    post:
      tags:
        - Workspace
      summary: Invite users to a group in a workspace
      description: Invites a user to a group in a workspace.
      operationId: post-api-workspace.group.invite
      security:
        - OAuth2Application:
            - 'workspace:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/emoji.listByWorkspace:
    get:
      tags:
        - Workspace
      summary: Retrieve a custom emoji list from a workspace
      description: Retrieve the list of custom emojis used in a given workspace
      operationId: '[GET]/api/emoji.listByWorkspace'
      security:
        - OAuth2Application:
            - 'workspace:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
  /api/channel.info:
    get:
      tags:
        - Channel
      summary: Get a channel's information
      description: Retrieves information about a channel.
      operationId: channel.info
      security:
        - OAuth2Application:
            - 'channel:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/channel.list:
    get:
      tags:
        - Channel
      summary: List out channels
      description: "Lists out a given number of channels from a workspace. This method uses the Swit API's [pagination scheme](/docs/core1/up49a503iuknu-pagination-scheme)."
      operationId: channel.list
      security:
        - OAuth2Application:
            - 'channel:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/channel.create:
    post:
      tags:
        - Channel
      summary: Create a channel
      description: Creates a new channel in a workspace.
      operationId: channel.create
      security:
        - OAuth2Application:
            - 'channel:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/channel.update:
    post:
      tags:
        - Channel
      summary: Update a channel
      description: Updates an existing channel.
      operationId: channel.update
      security:
        - OAuth2Application:
            - 'channel:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/channel.user.list:
    get:
      tags:
        - Channel
      summary: List out channel members
      description: "Lists out a given number of members belonging to a channel. This method uses the Swit API's [pagination scheme](/docs/core1/up49a503iuknu-pagination-scheme)."
      operationId: channel.user.list
      security:
        - OAuth2Application:
            - 'channel:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/channel.user.invite:
    post:
      tags:
        - Channel
      summary: Invite a user to the channel
      description: Invites a user to a channel.
      operationId: channel.AddChannelUserInvite
      security:
        - OAuth2Application:
            - 'channel:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
  /api/channel.user.remove:
    post:
      tags:
        - Channel
      summary: Remove users from a channel
      description: Removes users from a channel
      operationId: channel.DelChannelUser
      security:
        - OAuth2Application:
            - 'channel:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
  /api/channel.archive:
    post:
      tags:
        - Channel
      summary: Archive/unarchive a channel
      description: Updates a channel's archiving status.
      operationId: channel.UpdateChannelArchive
      security:
        - OAuth2Application:
            - 'channel:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/message.info:
    get:
      tags:
        - Message
      summary: Get a message's information
      description: Retrieves information about a message.
      operationId: message.info
      security:
        - OAuth2Application:
            - 'message:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/message.list:
    get:
      tags:
        - Message
      summary: List out messages
      description: "Lists out a given number of messages in a channel. This method uses the Swit API's [pagination scheme](/docs/core1/up49a503iuknu-pagination-scheme)."
      operationId: message.list
      security:
        - OAuth2Application:
            - 'message:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/message.create:
    post:
      tags:
        - Message
      summary: Create a message
      description: Creates a message in a channel.
      operationId: message.create
      security:
        - OAuth2Application:
            - 'message:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/message.share:
    post:
      tags:
        - Message
      summary: Share a message to a channel
      description: Shares a message to a channel.
      operationId: post-api-message.share
      security:
        - OAuth2Application:
            - 'message:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/message.taskShare:
    post:
      tags:
        - Message
      summary: Share a task to a channel
      description: Shares a task to a channel.
      operationId: post-api-message.taskShare
      security:
        - OAuth2Application:
            - 'message:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/message.remove:
    post:
      tags:
        - Message
      summary: Delete a message
      description: Deletes a message in a channel.
      operationId: message.remove
      security:
        - OAuth2Application:
            - 'message:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/message.reaction.create:
    post:
      tags:
        - Message
      summary: React to a message
      description: Adds a reaction emoji to a message.
      operationId: message.reaction.create
      security:
        - OAuth2Application:
            - 'message:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/message.reaction.remove:
    post:
      tags:
        - Message
      summary: Remove a reaction emoji from a message
      description: Removes a reaction emoji from a message.
      operationId: message.reaction.remove
      security:
        - OAuth2Application:
            - 'message:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/message.comment.list:
    get:
      tags:
        - MessageComment
      summary: List out message comments
      description: "Lists out a given number of comments on a message. This method uses the Swit API's [pagination scheme](/docs/core1/up49a503iuknu-pagination-scheme)."
      operationId: message.comment.list
      security:
        - OAuth2Application:
            - 'message:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/message.comment.create:
    post:
      tags:
        - MessageComment
      summary: Comment on a message
      description: Posts a comment on a message.
      operationId: message.comment.create
      security:
        - OAuth2Application:
            - 'message:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/message.comment.remove:
    post:
      tags:
        - MessageComment
      summary: Delete a message comment
      description: Deletes a comment on a message.
      operationId: message.comment.remove
      security:
        - OAuth2Application:
            - 'message:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/message.comment.reactionCreate:
    post:
      tags:
        - MessageComment
      summary: React to a message comment
      description: Adds a reaction emoji to a message's comment.
      operationId: post-api-message.comment.reactionCreate
      security:
        - OAuth2Application:
            - 'message:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/idea.info:
    get:
      tags:
        - Idea
      summary: Get an idea's information
      description: Retrieves information about an idea.
      operationId: idea.info
      security:
        - OAuth2Application:
            - 'idea:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/idea.list:
    get:
      tags:
        - Idea
      summary: List out ideas
      description: "Lists out a given number of ideas in a channel. This method uses the Swit API's [pagination scheme](/docs/core1/up49a503iuknu-pagination-scheme)."
      operationId: idea.list
      security:
        - OAuth2Application:
            - 'idea:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/idea.create:
    post:
      tags:
        - Idea
      summary: Create an idea
      description: Creates a idea in a channel.
      operationId: idea.create
      security:
        - OAuth2Application:
            - 'idea:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/idea.remove:
    post:
      tags:
        - Idea
      summary: Delete an idea
      description: Deletes an idea in a channel.
      operationId: idea.remove
      security:
        - OAuth2Application:
            - 'idea:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/idea.reaction.create:
    post:
      tags:
        - Idea
      summary: React to an idea
      description: Adds a reaction emoji to an idea.
      operationId: idea.reaction.create
      security:
        - OAuth2Application:
            - 'idea:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/idea.reaction.remove:
    post:
      tags:
        - Idea
      summary: Remove a reaction emoji from an idea
      description: Removes a reaction emoji from an idea.
      operationId: idea.reaction.remove
      security:
        - OAuth2Application:
            - 'idea:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/idea.comment.list:
    get:
      tags:
        - IdeaComment
      summary: List out idea comments
      description: "Lists out a given number of comments on an idea. This method uses the Swit API's [pagination scheme](/docs/core1/up49a503iuknu-pagination-scheme)."
      operationId: idea.comment.list
      security:
        - OAuth2Application:
            - 'idea:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/idea.comment.create:
    post:
      tags:
        - IdeaComment
      summary: Comment on an idea
      description: Posts a comment on an idea.
      operationId: idea.comment.create
      security:
        - OAuth2Application:
            - 'idea:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/idea.comment.remove:
    post:
      tags:
        - IdeaComment
      summary: Delete an idea comment
      description: Deletes a comment on an idea.
      operationId: idea.comment.remove
      security:
        - OAuth2Application:
            - 'idea:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/project.info:
    get:
      tags:
        - Project
      summary: Get a project's information
      description: Retrieves information about a project.
      operationId: project.info
      security:
        - OAuth2Application:
            - 'project:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/project.list:
    get:
      tags:
        - Project
      summary: List out projects
      description: "Lists out a given number of projects from a workspace. This method uses the Swit API's [pagination scheme](/docs/core1/up49a503iuknu-pagination-scheme)."
      operationId: project.list
      security:
        - OAuth2Application:
            - 'project:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/project.create:
    post:
      tags:
        - Project
      summary: Create a project
      description: Creates a project in a workspace.
      operationId: project.create
      security:
        - OAuth2Application:
            - 'project:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/project.update:
    post:
      tags:
        - Project
      summary: Update a project
      description: Updates an existing project in a workspace.
      operationId: project.update
      security:
        - OAuth2Application:
            - 'project:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/project.archive:
    post:
      tags:
        - Project
      summary: Archive/unarchive a project
      description: Updates a project's archiving status.
      operationId: project.UpdateProjectArchive
      security:
        - OAuth2Application:
            - 'project:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/project.user.list:
    get:
      tags:
        - Project
      summary: List out project members
      description: "Lists out a given number of members belonging to a project. This method uses the Swit API's [pagination scheme](/docs/core1/up49a503iuknu-pagination-scheme)."
      operationId: project.user.list
      security:
        - OAuth2Application:
            - 'project:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/project.user.invite:
    post:
      tags:
        - Project
      summary: Invite users to a project
      description: Invites users to a project.
      operationId: post-api-project.user.invite
      security:
        - OAuth2Application:
            - 'project:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/project.tagList:
    get:
      tags:
        - Project
      summary: List out task tags
      description: |-
        Lists out all task tags used in a project.

        Assigned to tasks of a project, tags facilitate filtering or searching
        those tasks for viewing convenience. This method enumerates all tags
        assigned at least once to any task of the target project.
      operationId: project.tagList
      security:
        - OAuth2Application:
            - 'project:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/task.status.list:
    get:
      tags:
        - Project
      summary: List out statuses in a project
      description: Lists out the list of statuses in a given project.
      operationId: task.status.list
      security:
        - OAuth2Application:
            - 'task:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/project.bucket.info:
    get:
      tags:
        - ProjectBucket
      summary: Get a task bucket's information
      description: Retrieves information about a task bucket.
      operationId: project.bucket.info
      security:
        - OAuth2Application:
            - 'project:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/project.bucket.list:
    get:
      tags:
        - ProjectBucket
      summary: List out task buckets
      description: Lists out all task buckets from a project.
      operationId: project.bucket.list
      security:
        - OAuth2Application:
            - 'project:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/project.bucket.create:
    post:
      tags:
        - ProjectBucket
      summary: Add a task bucket
      description: Adds a task bucket in a project.
      operationId: project.bucket.create
      security:
        - OAuth2Application:
            - 'project:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/project.bucket.update:
    post:
      tags:
        - ProjectBucket
      summary: Update a task bucket
      description: Updates the title of an existing task bucket in a project.
      operationId: project.bucket.update
      security:
        - OAuth2Application:
            - 'project:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/task.info:
    get:
      tags:
        - Task
      summary: Get a task's information
      description: Retrieves information about a task.
      operationId: task.info
      security:
        - OAuth2Application:
            - 'task:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/task.list:
    get:
      tags:
        - Task
      summary: List out tasks
      description: "Lists out a given number of tasks from a project. This method uses the Swit API's [pagination scheme](/docs/core1/up49a503iuknu-pagination-scheme)."
      operationId: task.list
      security:
        - OAuth2Application:
            - 'task:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/task.listByColumn:
    get:
      tags:
        - Task
      summary: List out tasks by bucket
      description: "Lists out a given number of tasks from a bucket. This method uses the Swit API's [pagination scheme](/docs/core1/up49a503iuknu-pagination-scheme)."
      operationId: task.listByColumn
      security:
        - OAuth2Application:
            - 'task:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/task.myTaskList:
    get:
      tags:
        - Task
      summary: List out my tasks
      description: Lists out "my tasks" of the user from a workspace.
      operationId: task.myTaskList
      security:
        - OAuth2Application:
            - 'task:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/task.create:
    post:
      tags:
        - Task
      summary: Create a task
      description: Creates a task in a project.
      operationId: task.create
      security:
        - OAuth2Application:
            - 'task:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/task.remove:
    post:
      tags:
        - Task
      summary: Delete a task
      description: Deletes a task from a project.
      operationId: task.remove
      security:
        - OAuth2Application:
            - 'task:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/task.move:
    post:
      tags:
        - Task
      summary: Move a task
      description: Moves a task into another project.
      operationId: task.move
      security:
        - OAuth2Application:
            - 'task:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/task.update:
    post:
      tags:
        - Task
      summary: Update a task
      description: Updates a task in a project.
      operationId: task.update
      security:
        - OAuth2Application:
            - 'task:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/task.assignee.add:
    post:
      tags:
        - Task
      summary: Add an assignee
      description: Adds an assignee to a task.
      operationId: task.assignee.add
      security:
        - OAuth2Application:
            - 'task:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/task.assignee.remove:
    post:
      tags:
        - Task
      summary: Remove an assignee
      description: Removes a member from the managing role for a task.
      operationId: task.assignee.remove
      security:
        - OAuth2Application:
            - 'task:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/task.follow.add:
    post:
      tags:
        - Task
      summary: Add a collaborator
      description: Adds a collaborator to a task.
      operationId: task.follow.add
      security:
        - OAuth2Application:
            - 'task:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/task.follow.remove:
    post:
      tags:
        - Task
      summary: Remove a collaborator
      description: Removes a collaborator from a task.
      operationId: task.follow.remove
      security:
        - OAuth2Application:
            - 'task:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/task.status.update:
    post:
      tags:
        - Task
      summary: Update the status of a task
      description: Updates the status of a task.
      operationId: task.status.update
      security:
        - OAuth2Application:
            - 'task:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/task.asset.append:
    post:
      tags:
        - Task
      summary: Add attachments
      description: Adds file attachments to a task.
      operationId: task.asset.append
      security:
        - OAuth2Application:
            - 'task:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
  /api/task.checklist.create:
    post:
      tags:
        - TaskChecklist
      summary: Add a checklist item
      description: Adds an item to a task's checklist.
      operationId: task.checklist.create
      security:
        - OAuth2Application:
            - 'task:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/task.checklist.info:
    get:
      tags:
        - TaskChecklist
      summary: Get a checklist item's information
      description: Retrieves information about a checklist item in a task.
      operationId: task.checklist.info
      security:
        - OAuth2Application:
            - 'task:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/task.checklist.list:
    get:
      tags:
        - TaskChecklist
      summary: List out checklist items
      description: "Lists out a given number of items from a task's checklist. This method uses the Swit API's [pagination scheme](/docs/core1/up49a503iuknu-pagination-scheme)."
      operationId: task.checklist.list
      security:
        - OAuth2Application:
            - 'task:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/task.checklist.remove:
    post:
      tags:
        - TaskChecklist
      summary: Delete a checklist item
      description: Deletes an item in a task's checklist.
      operationId: task.checklist.remove
      security:
        - OAuth2Application:
            - 'task:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/task.checklist.update:
    post:
      tags:
        - TaskChecklist
      summary: Update a checklist item
      description: Updates an existing item of a task's checklist.
      operationId: task.checklist.update
      security:
        - OAuth2Application:
            - 'task:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/task.comment.create:
    post:
      tags:
        - TaskComment
      summary: Comment on a task
      description: Posts a comment on a task.
      operationId: task.comment.create
      security:
        - OAuth2Application:
            - 'task:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/task.comment.list:
    get:
      tags:
        - TaskComment
      summary: List out task comments
      description: "Lists out a given number of comments on a task. This method uses the Swit API's [pagination scheme](/docs/core1/up49a503iuknu-pagination-scheme)."
      operationId: task.comment.list
      security:
        - OAuth2Application:
            - 'task:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/task.comment.remove:
    post:
      tags:
        - TaskComment
      summary: Delete a task comment
      description: Deletes a comment on a task.
      operationId: task.comment.remove
      security:
        - OAuth2Application:
            - 'task:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/task.comment.update:
    post:
      tags:
        - TaskComment
      summary: Edit a task comment
      description: Edits a comment on a task.
      operationId: task.comment.update
      security:
        - OAuth2Application:
            - 'task:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/contents.info:
    get:
      tags:
        - DirectMessage
      summary: Get a chat message's information
      description: Retrieves information about a chat message.
      operationId: content
      security:
        - OAuth2Application:
            - 'message:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/contents.list:
    get:
      tags:
        - DirectMessage
      summary: List out posts
      description: "Lists out a given number of posts in a chat. This method uses the Swit API's [pagination scheme](/docs/core1/up49a503iuknu-pagination-scheme)."
      operationId: content.list
      security:
        - OAuth2Application:
            - 'message:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/contents.create:
    post:
      tags:
        - DirectMessage
      summary: Create a chat message
      description: Creates a chat message.
      operationId: contents.create
      security:
        - OAuth2Application:
            - 'message:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/contents.update:
    post:
      tags:
        - DirectMessage
      summary: Update a chat message
      description: Updates a chat message.
      operationId: contents.update
      security:
        - OAuth2Application:
            - 'message:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/contents.delete:
    post:
      tags:
        - DirectMessage
      summary: Delete a chat message
      description: Deletes a chat message.
      operationId: contents.delete
      security:
        - OAuth2Application:
            - 'message:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/room.info:
    get:
      tags:
        - Conversation
      summary: Get a chat's information
      description: Retrieves information about a chat.
      operationId: room.info
      security:
        - OAuth2Application:
            - 'channel:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/room.list:
    get:
      tags:
        - Conversation
      summary: List out chats
      description: "Lists out a given number of chats. This method uses the Swit API's [pagination scheme](/docs/core1/up49a503iuknu-pagination-scheme)."
      operationId: room.list
      security:
        - OAuth2Application:
            - 'channel:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/room.create:
    post:
      tags:
        - Conversation
      summary: Create a chat
      description: "Creates a new chat. If a 1:1 chat with the specified member already exists, the response will not create a duplicate but instead return the existing chat's information. For group chats with specified members, a new chat will be created even if one already exists with the same members."
      operationId: room.create
      security:
        - OAuth2Application:
            - 'channel:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/room.update:
    post:
      tags:
        - Conversation
      summary: Update a chat
      description: Updates an existing chat.
      operationId: room.update
      security:
        - OAuth2Application:
            - 'channel:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/room.leave:
    post:
      tags:
        - Conversation
      summary: Leave a chat
      description: The use leaves a chat.
      operationId: room.levae
      security:
        - OAuth2Application:
            - 'channel:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/room.invite:
    post:
      tags:
        - Conversation
      summary: Invite people
      description: Invites people to a chat.
      operationId: room.invite
      security:
        - OAuth2Application:
            - 'channel:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/customfield.list:
    get:
      tags:
        - CustomField
      summary: List out custom fields
      description: Lists out all registered custom fields.
      operationId: customfield.list
      security:
        - OAuth2Application:
            - 'user:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/customfield.add:
    post:
      tags:
        - CustomField
      summary: Add a custom field
      description: Adds a new custom field for user profiles.
      operationId: customfield.add
      security:
        - OAuth2Application:
            - 'admin:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/customfield.delete:
    post:
      tags:
        - CustomField
      summary: Delete custom field
      description: Deletes a custom field for user profiles.
      operationId: customfield.delete
      security:
        - OAuth2Application:
            - 'admin:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/customfield.update:
    post:
      tags:
        - CustomField
      summary: Update a custom field
      description: Updates an existing custom field.
      operationId: customfield.update
      security:
        - OAuth2Application:
            - 'admin:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/customfield.user.list:
    get:
      tags:
        - CustomField
      summary: List out a user's custom fields in use
      description: Retrieves the custom fields and their values used in a given user's profile.
      operationId: customfield.user.list
      security:
        - OAuth2Application:
            - 'user:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/customfield.user.update:
    post:
      tags:
        - CustomField
      summary: Update a user's custom field data
      description: Updates the values of the custom fields used in a given user's profile.
      operationId: customfield.user.update
      security:
        - OAuth2Application:
            - 'admin:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/approval.create:
    post:
      tags:
        - Approval
      summary: Draft a request
      description: Creates a request draft for approval.
      operationId: approval.CreateApproval
      security:
        - OAuth2Application:
            - 'approval:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/approval.list.received:
    get:
      tags:
        - Approval
      summary: List out received requests
      description: "Lists out a given number of requests from the user's inbox. This method uses the Swit API's [pagination scheme](/docs/core1/up49a503iuknu-pagination-scheme)."
      operationId: approval.GetApprovalListReceived
      security:
        - OAuth2Application:
            - 'approval:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/approval.list.sent:
    get:
      tags:
        - Approval
      summary: List out submitted requests
      description: "Lists out a given number of requests from the user's submissions. This method uses the Swit API's [pagination scheme](/docs/core1/up49a503iuknu-pagination-scheme)."
      operationId: approval.GetApprovalListSent
      security:
        - OAuth2Application:
            - 'approval:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/approval.list.temp:
    get:
      tags:
        - Approval
      summary: List out drafts
      description: "Lists out a given number of request drafts. This method uses the Swit API's [pagination scheme](/docs/core1/up49a503iuknu-pagination-scheme)."
      operationId: approval.GetApprovalListTemp
      security:
        - OAuth2Application:
            - 'approval:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/approval.category.info:
    get:
      tags:
        - Approval
      summary: Get a template's info
      description: Retrieves information about a request template.
      operationId: approval.GetApprovalCategoryInfo
      security:
        - OAuth2Application:
            - 'approval:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/approval.category.list:
    get:
      tags:
        - Approval
      summary: List out templates
      description: "Lists out a given number of request templates. This method uses the Swit API's [pagination scheme](/docs/core1/up49a503iuknu-pagination-scheme)."
      operationId: approval.GetApprovalCategoryList
      security:
        - OAuth2Application:
            - 'approval:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
  /api/organization.user.info:
    get:
      tags:
        - Membership
      summary: Get user information
      description: Retrieves information of a user in the organization.
      operationId: organization.user.info
      security:
        - OAuth2Application:
            - 'user:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
  /api/organization.user.list:
    get:
      tags:
        - Membership
      summary: Get user list
      description: Retrieves a list of users in the organization.
      operationId: organization.user.list
      security:
        - OAuth2Application:
            - 'user:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
  /api/organization.user.create:
    post:
      tags:
        - Membership
      summary: Create a user
      description: Creates a user in the organization.
      operationId: organization.user.create
      security:
        - OAuth2Application:
            - 'admin:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
  /api/user.organization.batchCreate:
    post:
      tags:
        - Membership
      summary: Create guest accounts
      description: |-
        Invites multiple users as guests to the organization.

        > Calling this endpoint to create a user will not trigger an event notification for subscribers to the user creation event.
      operationId: user.organization.batchCreate
      deprecated: true
      security:
        - OAuth2Application:
            - 'admin:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
  /api/organization.user.activate:
    post:
      tags:
        - Membership
      summary: Activate a user
      description: Activates a user in an organization.
      operationId: organization.user.activate
      security:
        - OAuth2Application:
            - 'admin:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
  /api/organization.user.deactivate:
    post:
      tags:
        - Membership
      summary: Deactivate a user
      description: Deactivates a user in the organization.
      operationId: organization.user.deactivate
      security:
        - OAuth2Application:
            - 'admin:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
  /api/organization.user.remove:
    post:
      tags:
        - Membership
      summary: Delete a user
      description: Deletes a user from the organization.
      operationId: organization.user.remove
      security:
        - OAuth2Application:
            - 'admin:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
  /api/user.team.list:
    get:
      tags:
        - Team
      summary: List out teams
      description: 'List out the child teams of a given team. If no parameters are passed, the list of all teams in the organization is given as a response.'
      operationId: user.team.list
      security:
        - OAuth2Application:
            - 'user:read'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
  /api/team.create:
    post:
      tags:
        - Team
      summary: Create a team
      description: Creates a new team in the organization.
      operationId: team.create
      security:
        - OAuth2Application:
            - 'admin:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
  /api/team.update:
    post:
      tags:
        - Team
      summary: Update a team
      description: Updates a team's information including its name and parent team.
      operationId: team.update
      security:
        - OAuth2Application:
            - 'admin:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
  /api/team.delete:
    post:
      tags:
        - Team
      summary: Delete a team
      description: Deletes a team.
      operationId: team.delete
      security:
        - OAuth2Application:
            - 'admin:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
  /api/team.sort:
    post:
      tags:
        - Team
      summary: Sort teams
      description: Sort the child teams of a parent team in a given order.
      operationId: team.sort
      security:
        - OAuth2Application:
            - 'admin:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
  /api/team.user.add:
    post:
      tags:
        - Team
      summary: Add users to a team
      description: Adds users to a team.
      operationId: team.user.add
      security:
        - OAuth2Application:
            - 'admin:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
  /api/team.user.primary.update:
    post:
      tags:
        - Team
      summary: Update a user's primary team
      description: Updates a user's primary team.
      operationId: team.user.primary.update
      security:
        - OAuth2Application:
            - 'admin:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
  /api/team.user.remove:
    post:
      tags:
        - Team
      summary: Remove team members
      description: Removes members from a team.
      operationId: team.user.remove
      security:
        - OAuth2Application:
            - 'admin:write'
      servers:
        - url: 'https://openapi.swit.io/v1'
          description: Production
        - url: 'https://openapi.swit.express/v1'
          description: Stage
        - url: 'https://openapi2.swit.dev/v1'
          description: Development
      x-internal: false
tags:
  - name: User
    description: description
  - name: Workspace
    description: description
  - name: Channel
    description: description
  - name: Message
    description: description
  - name: MessageComment
    description: description
  - name: Idea
    description: description
  - name: IdeaComment
    description: description
  - name: Project
    description: description
  - name: ProjectBucket
    description: description
  - name: Task
    description: description
  - name: TaskChecklist
    description: description
  - name: TaskComment
    description: description
  - name: DirectMessage
    description: description
  - name: Conversation
    description: description
  - name: CustomField
    description: description
  - name: Approval
    description: description
  - name: Membership
    description: description
  - name: Team
    description: description
  - name: Email
    description: description
  - name: Interface
    description: description
  - name: Automation
    description: description
  - name: SecurityCDN
    description: description
  - name: Task-ISC
    description: description
components:
  securitySchemes:
    OAuth2Application:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://openapi.swit.io/oauth/authorize'
          scopes:
            'user:write': 'Edit the authorizing user’s account information, profile, and settings'
            'presence:write': Change the authorizing user’s presence status
            'presence:read': View the authorizing user’s presence status
            'approval:write': 'Edit your organization’s Approvals plug-in settings, and draft and submit approval requests'
            'approval:read': 'View your organization’s Approvals plug-in settings, and view approval requests accessible to the authorizing user'
            'admin:write': 'Edit your organization’s administrative settings, membership and teams'
            'admin:read': 'View your organization’s administrative settings, membership and teams'
            'workspace:write': Create and edit workspaces
            'workspace:read': View information about workspaces
            'user:read': 'View the authorizing user’s account information, profile, and settings'
            'task:write': Create and edit tasks in projects the authorizing user is in
            'task:read': View tasks posted to projects the authorizing user is in
            'project:write': Create and edit projects
            'project:read': View information about projects
            'message:write': Create and edit messages in channels the authorizing user is in
            'message:read': View messages posted to channels the authorizing user is in
            'idea:write': Create and edit ideas in channels the authorizing user is in
            'idea:read': View ideas posted to channels the authorizing user is in
            'channel:write': Create and edit channels
            'channel:read': View information about channels
            'app:install': Add the bot user and extended UI elements for users to interact with the app server
            'store:write': Create and delete event subscriptions for the authorizing user’s account
            'imap:write': Connect to an IMAP server and read email.
            'imap:read': Fetch email details using IMAP.
          tokenUrl: 'https://openapi.swit.io/oauth/token'
